// <auto-generated />
namespace SKIN_CARE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AccountDatelindje : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AccountDatelindje));
        
        string IMigrationMetadata.Id
        {
            get { return "202106061643118_AccountDatelindje"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
